name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          git clone https://gitlab.com/tearch-linux/applications-and-tools/teaiso -b rw
          cd teaiso
          pacman -Sy xorriso grub mtools make python \
             dosfstools e2fsprogs squashfs-tools python-yaml \
             gcc wget curl --noconfirm libisoburn
          make
          git clone https://gitlab.com/tearch-linux/configs/tearch-iso-profiles
          exec sudo ./mkteaiso --profile=tearch-iso-profiles/editions/pantheon --output=/chroot/output/ --debug 2>&1


      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: chroot/output/*
